### ISSUE TITLE
"Vs/cm2"

### ISSUE THREAD

**Issue by germa** [bio-ontology-research-group/unit-ontology#14]
Hello,

I would like to propose a new unit term, which is used ion ion mobility spectrometry

[Term]
id: UO:0000xxx
name: volt-second per square centimeter
def: "An electrical mobility unit which is equal to one volt second per square centimeter."
synonym: "Vs/cm^2" EXACT [] 

Best regards,
Gerhard Mayer
PRIDE team

**Comment by reality** [comment]
Added en https://github.com/bio-ontology-research-group/unit-ontology/commit/f17a7881c2518924435865cc052a72ffb811fbe8
