### ISSUE TITLE
typo of UO_0000036:'year' definition

### ISSUE THREAD

**Issue by zhengj2007** [bio-ontology-research-group/unit-ontology#15]
EuPathDB (http://eupathdb.org/) used UO. We found the definition of "year" contains a typo:
"A time unit which is equal to 12 months which is science is taken to be equal to 365.25 days."

should probably say: " ...which IN science..."?

Thanks!

**Comment by zhengj2007** [comment]
@leechuck @gkoutos 
Any comments on the issue? 

Thanks!

Jie

**Comment by leechuck** [comment]
@reality Could you please have a look?
