### ISSUE TITLE
Term request: micrograms per bottle

### ISSUE THREAD

**Issue by SAK22** [bio-ontology-research-group/unit-ontology#18]
Hi! Could we add the term microgram per bottle?

**Comment by reality** [comment]
Hi, certainly! Is there a reference for the definition of microgram per bottle you could provide? Is "bottle" a fixed unit, or would that be defined per-dataset? Would this also require a "bottle" term?

**Comment by SAK22** [comment]
Hi!

So we wouldn’t need a bottle term as well. A ‘bottle’ is a fixed unit for these kind of experiments (monitoring insecticide resistance) which are Center of Disease Control standard protocol.
The bottle is a 250ml wheaton bottle.

Maybe the definition could be: A unit of mass concentration defined as the number of micrograms of a substance per 250 ml Wheaton bottle.

Edit the definition as you see fit!

Thank you

Sarah

On 2019Mar29, at 21:30, Luke Slater <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, certainly! Is there a reference for the definition of microgram per bottle you could provide? Is "bottle" a fixed unit, or would that be defined per-dataset? Would this also require a "bottle" term?

**Comment by reality** [comment]
the class has been added, with id UO:0010053. sorry for the delay!
