### ISSUE TITLE
Term request: pounds per square inch

### ISSUE THREAD

**Issue by chambm** [bio-ontology-research-group/unit-ontology#20]
We Americans need this term to keep our tires inflated properly! Also sometimes chromatography pump pressure, apparently. Thanks!

[Term]
id: UO:0000xxx
name: pounds per square inch
namespace: unit.ontology
def: "A pressure unit which is equal to 6894.757 pascal." [Wikipedia:Wikipedia]
synonym: "psi" EXACT []
synonym: "lbf/in^[2]" EXACT []
is_a: UO:0000109 ! pressure unit

**Comment by chambm** [comment]
@reality Is there a way to create a PR just from editing the OBO? I.e. some script that will create all the OWL changes? (or vice versa, I suppose)

**Comment by reality** [comment]
Hello, I've added the term with ID UO:0010052. Sorry for the long delay. For future reference, you can edit the OBO file yourself, and then simply run 'groovy unitsconverter unit.obo' to generate the other files. With that run you can submit a pullreq.
