### ISSUE TITLE
Term request: gram per square meter

### ISSUE THREAD

**Issue by zhengj2007** [bio-ontology-research-group/unit-ontology#22]
Name | Value
-- | -- 
Label | gram per square meter
Definition | An area density unit which is equal to the mass of an object in grams divided by the surface area in meters squared.
Definition source | EFO_0002898 gram per meter squared 
Parent | UO_0000054 area density unit
alternative term | gram per metre squared, g/m^2, gram per square meter 

Request by VEuPathDB (https://eupathdb.org/)

**Comment by zhengj2007** [comment]
@reality Could you please help on this term? Thanks!

**Comment by reality** [comment]
Hi, the new term ID is UO:0000013

**Comment by zhengj2007** [comment]
@reality Thanks a lot for it!
