### ISSUE TITLE
Request for PURL for uo-without-units-as-classes.owl

### ISSUE THREAD

**Issue by dillerm** [bio-ontology-research-group/unit-ontology#23]
We're interested in importing uo-without-units-as-classes.owl, but cannot do so without a working PURL.

**Comment by leechuck** [comment]
I am not entirely sure how to do this, I think it would have to be configured at the OBO side with their purl system; any ideas @reality @cmungall ?

**Comment by dillerm** [comment]
You should be able to edit the yaml file in the purl.obolibrary.org Github. Here is an example of how we did it with GEO (see everything under "entries"): https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/geo.yml.

**Comment by reality** [comment]
solved by above
