### ISSUE TITLE
NTRs - units needed in agronomic experiments

### ISSUE THREAD

**Issue by celineaubert** [bio-ontology-research-group/unit-ontology#24]
Could you please add the following units:?
- Square meter per second : unit of kinematic viscosity, specific relative angular momentum and thermal diffusivity. synonym: m2/s, m2·s−1, m2s−1. 
- centimole charge per kilogram (synonym: cmolc/kg): Unit of the cation-exchange capacity. equivalent units me/100g or meq/100g
- decisiemens per metre (synonym:dS/m): https://www.naturalresources.sa.gov.au/samurraydarlingbasin/publications/measuring-salinity
- microgram per gram: A mass unit density which is equal to mass of an object in micrograms divided by the mass in grams. 
- gram per kilogram: A mass unit density which is equal to mass of an object in grams divided by the mass in kilograms. g/kg
- Feet per second: A speed/velocity unit which is equal to the speed of an object traveling 1-foot distance in one second. synonym: ft/s
- Miles per hour: A speed/velocity unit which is equal to the speed of an object traveling 1-mile distance in one hour. synonym: mi/h
- gram per square meter: An area density unit which is equal to the mass of an object in grams divided by the surface area in hectares. synonym: g/m2
- Pound per hectare: An area density unit which is equal to the mass of an object in pounds divided by the surface area in hectares. synonym: lb/ha
- Bushel: A unit volume equivalent to 8 US dry gallons https://en.wikipedia.org/wiki/Bushel . synonym: bsh
- Quintal: A mass unit equivalent to 100 kilograms - synonym: q
- Square foot: An area unit which is equal to an area enclosed by a square with sides each 1 foot . synonym: ft2, sq. ft, sf.
- gram per square meter: An area density unit which is equal to the mass of an object in grams divided by the surface area in meters squared. synonym: g/m2
- gram per square foot: An area density unit which is equal to the mass of an object in grams divided by the surface area in feet squared. synonym: g/ft2
- pound per acre: An area density unit which is equal to the mass of an object in pounds divided by the surface area in acres. synonym lb/ac
- milliliter per square meter: A volume density unit? which is equal to the volume of an object in milliliters divided by the surface area in meters squared. synonym: mm/m2
- liter per hectare: A volume density unit? unit which is equal to the volume of an object in liters divided by the surface area in hectares. synonym: l/ha
- liter per acre: A volume density unit? unit which is equal to the volume of an object in liters divided by the surface area in acres. synonym: l/ac 
- liter per square meter: A volume density unit? unit which is equal to the volume of an object in liters divided by the surface area in meters squared. synonym: l/m2
- liter per square foot: A volume density unit? unit which is equal to the volume of an object in liters divided by the surface area in feet squared. l/ft2
- ton per acre: An area density unit which is equal to the mass of an object in tons divided by the surface area in acres. synonym: t/ac
- pound per square foot: An area density unit which is equal to the mass of an object in pounds divided by the surface area in feet squared. synonym: lb/ft2
- bushel per acre: An area density unit which is equal to the mass of an object in bushels divided by the surface area in acres. synonym: bsh/ac
- quintal per acre: An area density unit which is equal to the mass of an object in quintals divided by the surface area in acres. synonym: q/ac
- quintal per hectare: An area density unit which is equal to the mass of an object in quintals divided by the surface area in hectares. synonym: q/ha
- ton per acre: An area density unit which is equal to the mass of an object in tons divided by the surface area in acres. t/ac
- m3/ha

@marieALaporte

**Comment by celineaubert** [comment]
Hello,

We would need to have the terms above in our ontology soon. Do you think you will be able to add then in UO within two weeks? If it is not possible on your side, we will add them in AgrO and deprecate them once you add then in UO.
Thanks!

**Comment by marieALaporte** [comment]
@krishnaTO can you make a PR for those? Thanks

**Comment by KrishnaTO** [comment]
Added PR for terms with following notes:

Terms already exist:
- gram per square meter
- ton per hectares

Terms are classes which define the conversion between prefixes, are they required as distinct classes?
- gram per kilogram
- microgram per gram
