### ISSUE TITLE
Interest in contributing to UO/uo-idranges.owl

### ISSUE THREAD

**Issue by kaiiam** [bio-ontology-research-group/unit-ontology#25]
Hello UO team and @reality, My name is Kai Blumberg, I'm a developer for the Environment Ontology (ENVO). I'm working on a project [Planet Microbe](https://www.planetmicrobe.org/) in which I am using various OBO ontologies including UO to make marine metagenomic datasets interoperable. I have about 20 terms, I'd be interested in adding to UO, (e.g., bar, decibar, atmosphere unit). 

Let me know if this would be possible and how you would prefer I do so. If I should post issues, or if you might be interested in having me make pull requests or be a direct contributor. 

Thanks

-Kai

**Comment by kaiiam** [comment]
Thank you @leechuck for adding me as a contributor! 

As my first order of business as we discussed via email, I will add a `uo-idranges.owl` file, and will make this issue about that.

**Comment by kaiiam** [comment]
xref #27

**Comment by chambm** [comment]
Hi @kaiiam what happened to adding bar, decibar, etc?

**Comment by kaiiam** [comment]
Hey @chambm thanks for reaching out, unfortunately I didn't end up having time to work on UO. A number of us opted instead to build https://units-of-measurement.org/. We did some mappings there, happy to help use that to inform you guys of concepts in other units ontologies that UO is missing. 

Cheers,
Kai
