### ISSUE TITLE
NTR: calorie

### ISSUE THREAD

**Issue by ddooley** [bio-ontology-research-group/unit-ontology#26]
label: large calorie
definition: A unit of energy widely used in nutrition, equivalent to the amount of heat needed to cause one kilogram of water to rise in temperature by one degree Celsius.
definition source: https://en.wikipedia.org/wiki/Calorie
parent: energy unit
example of use: "There probably are a lot of brands out there that use the large calorie in their labels to avoid big, intimidating numbers"
synonyms: food calorie, kilocalorie, big calorie, Cal, Calorie, calorie or kcal
requestor: Damion Dooley
comment: "By convention in food science, the large calorie is commonly called calorie (with a capital C by some authors to distinguish from the smaller unit)" [Wikipedia]

**Comment by ddooley** [comment]
I think this one is ready to go?!

**Comment by reality** [comment]
Have added this term with ID UO:0010051. sorry for the delay!

**Comment by ddooley** [comment]
Thanks!
