### ISSUE TITLE
Synonyms not present in OWL

### ISSUE THREAD

**Issue by wdduncan** [bio-ontology-research-group/unit-ontology#33]
In the OWL version of UO, I am not finding synonyms. For example, kilogram has synonym kg on [OLS](https://www.ebi.ac.uk/ols/ontologies/uo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUO_0000009). But this is not given in uo.owl.

cc @cmungall

**Comment by cmungall** [comment]
I can confirm this:

```bash
$ curl -L -s http://purl.obolibrary.org/obo/uo.owl | grep kg
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">&quot;A mass unit which is equal to one thousandth of a kilogram or 10^[-3] kg.&quot; [NIST:NIST]</rdfs:comment>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">&quot;A unit of concentration which expresses a concentration of a solution of 1 mole per kilogram of solvent (mol/kg).&quot; [UOC:GVG]</rdfs:comment>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">&quot;A specific volume unit which is equal to a thousandth of a liter per kilogram or 10^[-3] l/kg.&quot; [NIST:NIST]</rdfs:comment>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">&quot;A specific volume unit which is equal to one millionth of a liter per kilogram or 10^[-6] l/kg.&quot; [NIST:NIST]</rdfs:comment>
```

no syns, just mentioned in comments

```
$ curl -L -s http://purl.obolibrary.org/obo/uo.obo | grep kg
synonym: "kg" EXACT []
def: "A mass unit which is equal to one thousandth of a kilogram or 10^[-3] kg." [NIST:NIST]
def: "A unit of concentration which expresses a concentration of a solution of 1 mole per kilogram of solvent (mol/kg)." [UOC:GVG]
synonym: "kg/m^[3]" EXACT []
synonym: "kg/m^[2]" EXACT []
synonym: "kg/mol" EXACT []
synonym: "kg.m/s" EXACT []
synonym: "m^[3]/kg" EXACT []
synonym: "kg/L" EXACT []
synonym: "kg/m" EXACT []
synonym: "l/kg" EXACT []
def: "A specific volume unit which is equal to a thousandth of a liter per kilogram or 10^[-3] l/kg." [NIST:NIST]
synonym: "ml/kg" EXACT []
def: "A specific volume unit which is equal to one millionth of a liter per kilogram or 10^[-6] l/kg." [NIST:NIST]
synonym: "ul/kg" EXACT []
```

@reality @leechuck is there something wrong with the release pipeline? I'm having a hard time with this repo figuring out which file is source (@kaiiam this may benefit from an odk revamp)

**Comment by kaiiam** [comment]
@cmungall my understanding from what @reality told me is that:

> The current workflow is essentially: 1. edit unit.obo 2. run unitsconverter.groovy to generate the additional files. 

If it's desired by the senior UO team, I'd be happy to try and do an ODK revamp of UO.

**Comment by reality** [comment]
Hello,

I think we discussed this before -- yes, we would be happy with an ODK revamp :-)

Thanks,
Luke

**Comment by cmungall** [comment]
Thanks Luke!

In the interim can we see if there is an easy fix to this particular issue? Does unitscnoverter wrap the owlapi? If so it is odd the synonyms don't show up in the owl - something else going on?

**Comment by kaiiam** [comment]
> yes, we would be happy with an ODK revamp :-)

Awesome thanks I'll try to get a PR going soon.

**Comment by reality** [comment]
that should do it. the synonyms were simply not added to the ontology by the wrapper script. if you can confirm that this solves the problem for your use case, then I'll close the issue :-)
