### ISSUE TITLE
NTRs for clinical measurements

### ISSUE THREAD

**Issue by johnwjudkins** [bio-ontology-research-group/unit-ontology#38]
We would like the addition of these units to the ontology:

kilometer
milligram per deciliter
microgram per deciliter
micromole per liter

**Comment by reality** [comment]
micromole per litre already added at UO:0010003

**Comment by reality** [comment]
added: 

- kilometre at UO:0010066
- milligram per deciliter at UO:0010067
- microgram per deciliter at UO:0010068

apologies for the delay in adding the terms.
