### ISSUE TITLE
unit.obo is missing a couple of dbxref lists in the def: tag

### ISSUE THREAD

**Issue by mwalzer** [bio-ontology-research-group/unit-ontology#44]
unit.obo is missing a couple of dbxref lists in the def: tag
IDK about owl, but for obo, this is a required feature for the term definition tag (if the tag is present). [At least in v1.4](http://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html#S.2.2), but it's probably not a new requirement.
Like here:
https://github.com/bio-ontology-research-group/unit-ontology/blob/f9ff25b49c9fac886a688a89505ea2ba57ecd05d/unit.obo#L1917

**Comment by mwalzer** [comment]
quick and dirty regex to find offending lines: `^def.*[^\]]$`

**Comment by bittremieux** [comment]
The format-version of the UO file is 1.2. However, a list of dbxrefs is necessary for that version as well: https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_2.html

It would be nice if this can be fixed for those terms where the dbxref is missing.

**Comment by cmungall** [comment]
@reality any chance of fixing this? Is this due to using the groovy obo writer rather than owlapi/robot?
