### ISSUE TITLE
UO is not parseable

### ISSUE THREAD

**Issue by matentzn** [bio-ontology-research-group/unit-ontology#54]
```
 robot -vvv merge -I http://purl.obolibrary.org/obo/uo.owl -o uo.owl
```

Causes other ontologies importing it to fail (like [MS](https://github.com/HUPO-PSI/psi-ms-CV/issues/138)).

Most likely culprit:

```
org.xml.sax.SAXParseException; systemId: http://purl.obolibrary.org/obo/uo.owl; lineNumber: 7563; columnNumber: 75; The prefix "dc" for element "dc:creator" is not bound.        org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:78)
```

But not sure if its the only one.

**Comment by leechuck** [comment]
@reality would you have time to look into this?

**Comment by bkr-iotic** [comment]
Hello, I have raised a PR to fix this #53

**Comment by leechuck** [comment]
Thank you; I merged the PR.

**Comment by bkr-iotic** [comment]
Good spot @matentzn, there were a bunch of new abbreviations added in that commit that needed to be literals, as well as an errant space in another IRI.

@leechuck please see #55, which parses for me.
