### ISSUE TITLE
OWL API throws a parser exception when trying to parse uo.owl

### ISSUE THREAD

**Issue by dillerm** [bio-ontology-research-group/unit-ontology#56]
org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=7751:column=57] IRI 'l/m^2' cannot be resolved against current base IRI http://purl.obolibrary.org/obo/uo.owl reason is: Illegal character in path at index 3: l/m^2

[Line in question](https://github.com/bio-ontology-research-group/unit-ontology/blob/master/uo.owl#L7751)

I believe changing that line to the following would fix this:
`<oboInOwl:hasExactSynonym xml:lang="en">l/m^2</oboInOwl:hasExactSynonym>`

**Comment by bkr-iotic** [comment]
#55 fixes this (and several other errors of this type)

**Comment by matentzn** [comment]
Yes, please fix this, and consider adding some QC - unparseable ontologies should really be a thing of the past!

**Comment by reality** [comment]
fixed by #55; parseability to be addressed in odk migration
