### ISSUE TITLE
Add 'µmoles per m2 per second' as an alternative label to microeinstein per square meter per second?

### ISSUE THREAD

**Issue by kristenpeach** [bio-ontology-research-group/unit-ontology#58]
Hello! I work at NASA's GeneLab ingesting plant spaceflight studies into out repository. I use UO all the time and I appreciate the effort you've put into it! I'm having some trouble finding appropriate units to describe light intensity in plant growth studies. The most common unit I see used to report light intensity is µmol/m2/s, which I don't see a defined class for in Ontobee/BioPortal. I see you have microeinstein per square meter per second, which I understand is equivalent. However, the Einstein is not a unit in the SI (International System) of units, so for our repository using moles is preferred. 

Would you be willing to make µmoles per m2 per second a synonym or alternative label to microeinstein per square meter per second?

Alternatively, does this already exist somewhere and I am just not seeing it?

Thank you for your help!
Kristen

**Comment by kristenpeach** [comment]
Friendly reminder to @reality we planned to add 'micromole per square meter per second' as an alternative label to 'microeinstein per square meter per second' when you have time :)

**Comment by reality** [comment]
also solved with other commit. thanks!
