### ISSUE TITLE
Can you add 'milligray per second' under radiation unit?

### ISSUE THREAD

**Issue by kristenpeach** [bio-ontology-research-group/unit-ontology#60]
Are you able to add a class 'milligray per second' to UO? The definition would be "A derived absorbed dose unit which is equal to one milligray absorbed per second". I've been using the other gray based units in UO and this is the only common radiation unit that is missing so it would be a big help to have it. Thank you!

**Comment by kristenpeach** [comment]
Also, while I am here bothering you, could you add "milligray per hour"? It would be so useful! I appreciate UO so much, thank you!

**Comment by reality** [comment]
these were added in https://github.com/bio-ontology-research-group/unit-ontology/commit/2a12cf584c44ed18f0f90c60606346e07d885a85 . Thank you
