### ISSUE TITLE
Error with oboInOwl header lines

### ISSUE THREAD

**Issue by janelomax** [bio-ontology-research-group/unit-ontology#62]
In the header of uo.owl you have:

`     xmlns:oboInOwl="oboInOwl:"
`
I think this should be:

`     xmlns:oboInOwl="http://www.geneontology.org/formats/oboInOwl#">
`

so that the URIs for ExactSynonym etc get built correctly.

**Comment by reality** [comment]
duplicate of https://github.com/bio-ontology-research-group/unit-ontology/issues/35 (and also fixed per that issue). Thank you!
