### ISSUE TITLE
Term request: kilograms per hectare 

### ISSUE THREAD

**Issue by pbuttigieg** [bio-ontology-research-group/unit-ontology#9]
Hi UO, we'd like to have a class: `kilograms per hectare`. `hectare` would need to be created in the `area` hierarchy.

`hectare` =def. a unit of area equal to 10,000 square meters: equivalent to 2.471 acres.

**Comment by celineaubert** [comment]
Hi,
This class is also needed in AgrO.

**Comment by reality** [comment]
Hi, UO:0000283 describes kilograms per hectare. The above commit adds hectare, with the ID UO:0010010. Cheers
